apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: 20pct
  namespace: kargo-canary
  annotations:
    kargo.akuity.io/color: cyan
spec:
  subscriptions:
    upstreamStages:
      - name: 05pct
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/jessesuen/kargo-canary.git
      writeBranch: main
      kustomize:
        images:
        - image: ghcr.io/jessesuen/rollouts-demo
          path: base/20pct
    argoCDAppUpdates:
    - appName: kargo-canary
