apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../deployment

nameSuffix: -75pct

labels:
- includeSelectors: true
  pairs:
    canary: 75pct
images:
- name: ghcr.io/jessesuen/rollouts-demo
  newName: ghcr.io/jessesuen/rollouts-demo
  newTag: purple
