apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-canary
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: kargo-canary
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app.kubernetes.io/name: kargo-canary
    spec:
      containers:
      - name: kargo-canary
        image: ghcr.io/jessesuen/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
